src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\Column(options:['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $comment_date = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Events $event = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Participants $participant = null;

    public function __construct()
    {
        $this->comment_date = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getCommentDate(): ?\DateTimeImmutable
    {
        return $this->comment_date;
    }

    public function setCommentDate(\DateTimeImmutable $comment_date): static
    {
        $this->comment_date = $comment_date;

        return $this;
    }

    public function getEvent(): ?Events
    {
        return $this->event;
    }

    public function setEvent(?Events $event): static
    {
        $this->event = $event;

        return $this;
    }

    public function getParticipant(): ?Participants
    {
        return $this->participant;
    }

    public function setParticipant(?Participants $participant): static
    {
        $this->participant = $participant;

        return $this;
    }
}

src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $quater = null;

    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $event_date = null;

    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Comments::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Images::class, orphanRemoval: true, cascade:['persist'])]
    private Collection $images;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $categorie = null;

    #[ORM\OneToMany(mappedBy: 'Ville', targetEntity: Filters::class)]
    private Collection $filters;


    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Participants::class, orphanRemoval: true)]
    private Collection $participants;

    #[ORM\OneToMany(mappedBy: 'events', targetEntity: Guests::class, orphanRemoval: true)]
    private Collection $guests;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->event_date = new \DateTimeImmutable();
        $this->created_at = new \DateTimeImmutable();
        $this->filters = new ArrayCollection();
        $this->participants = new ArrayCollection();
        $this->guests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getQuater(): ?string
    {
        return $this->quater;
    }

    public function setQuater(string $quater): static
    {
        $this->quater = $quater;

        return $this;
    }

    public function getEventDate(): ?\DateTimeImmutable
    {
        return $this->event_date;
    }

    public function setEventDate(\DateTimeImmutable $event_date): static
    {
        $this->event_date = $event_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setEvent($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getEvent() === $this) {
                $comment->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setEvent($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getEvent() === $this) {
                $image->setEvent(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categories
    {
        return $this->categorie;
    }

    public function setCategorie(?Categories $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Filters>
     */
    public function getFilters(): Collection
    {
        return $this->filters;
    }

    public function addFilter(Filters $filter): static
    {
        if (!$this->filters->contains($filter)) {
            $this->filters->add($filter);
            $filter->setVille($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Participants>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participants $participant): static
    {
        if (!$this->participants->contains($participant)) {
            $this->participants->add($participant);
            $participant->setEvent($this);
        }

        return $this;
    }

    public function removeParticipant(Participants $participant): static
    {
        if ($this->participants->removeElement($participant)) {
            // set the owning side to null (unless already changed)
            if ($participant->getEvent() === $this) {
                $participant->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Guests>
     */
    public function getGuests(): Collection
    {
        return $this->guests;
    }

    public function addGuest(Guests $guest): static
    {
        if (!$this->guests->contains($guest)) {
            $this->guests->add($guest);
            $guest->setEvents($this);
        }

        return $this;
    }

    public function removeGuest(Guests $guest): static
    {
        if ($this->guests->removeElement($guest)) {
            // set the owning side to null (unless already changed)
            if ($guest->getEvents() === $this) {
                $guest->setEvents(null);
            }
        }

        return $this;
    }

}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Comments;
use App\Entity\Events;
use App\Form\CommentFormType;
use App\Repository\CategoriesRepository;
use App\Repository\CommentsRepository;
use App\Repository\EventsRepository;
use App\Repository\ParticipantsRepository;
use App\Repository\UsersRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/', name: 'acceuil_')]
class MainController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(
        CategoriesRepository $categoriesRepository, 
        EventsRepository $eventsRepository): Response
    {
        return $this->render('main/index.html.twig', [
            'categories' => $categoriesRepository->findBy([], [
                'id' => 'asc'
            ]),
            'events' => $eventsRepository->findBy([], [
                'categorie' => 'asc'
            ])
        ]);
    }

    #[Route('/gerer', name:'manage')]
    public function manager() : Response
    {
        return $this->render('main/manage.html.twig');
    }

    #[Route('/tableaudebord', name: 'tableau')]
    public function tableau(EventsRepository $events, ParticipantsRepository $participants, CommentsRepository $commentsRepository)
    {
        $les = $events->findAll();
        $note = array();
        $a = array();

        // On initialise toutes les notes à 0
        foreach ($les as $key1 => $value1) {
            $note[$value1->getName()] = 0;
            $a[$value1->getName()] = 0;
        };

        // Remplir les notes de chaque event
        foreach ($les as $key => $val) {
            foreach ($val->getParticipants() as $key2 => $value) {

                if(isset($note[$val->getName()])) {
                    $note[$val->getName()] = $note[$val->getName()] + (($value->getNote() == null ) ? 0 : $value->getNote());
                    $a[$val->getName()] = ($value->getNote() != null ) ? $a[$val->getName()] + 1 : $a[$val->getName()] + 0; 

                } else {
                    $note[$val->getName()] = (($value->getNote() == null ) ? 0 : $value->getNote());
                    $a[$val->getName()] = ($value->getNote() != null ) ? $a[$val->getName()] + 1 : $a[$val->getName()] + 0; 
                }
            }
        }

        // Calcul de la moyenne des notes d'un event en %
        foreach ($les as $cle => $valeur) {
            if($note[$valeur->getName()] > 0){
                $note[$valeur->getName()] = (($note[$valeur->getName()] / $a[$valeur->getName()]) / 5) * 100;
            }
        }

        return $this->render('main/tableau.html.twig', [
            'events' => $events->findAll(),
            'participants' => $participants->findBy([], [], 3),
            'comments' => $commentsRepository->findBy([], [], 5),
            'notes' => $note
        ]);
    }
    
    /**
     * Renvoie les détails de l'événement
     */
    #[Route('/details/{id}', name: 'details')]
    public function details(Events $event, Request $request, EntityManagerInterface $em, ParticipantsRepository $participantsRepository, CommentsRepository $commentsRepository): Response
    {
        $comment = new Comments();
        // $comments = $event->getComments();
        $commentForm = $this->createForm(CommentFormType::class, $comment);

        $participants = $event->getParticipants();

        $a = 0;
        $note = 0;

        if($participants){

            for ($i=0; $i < count($participants); $i++) { 
                $note+= $participants[$i]->getNote();
                ($participants[$i]->getNote() > 0 ) ? $a++ : $a+=0;
            }
            if($note > 0){
                $note = ($note / $a) / 5 * 100;
            }
        }


        $commentForm->handleRequest($request);

        if($commentForm->isSubmitted() && $commentForm->isValid())
        {
            $participant = $participantsRepository->findOneBy(['user' => $this->getUser()]);
            if($participant){
                if($participant->getEvent() === $event) {

                    $comment->setEvent($event);
                    $comment->setParticipant($participantsRepository->findOneBy(['user' => $this->getUser()]));
                    $em->persist($comment);
                    $em->flush();
                    return $this->redirectToRoute('acceuil_details', ['id' => $event->getId()]);
                }

            }

            $this->addFlash('warning', 'Seuls les participants sont autorisés à commenter');
            return $this->redirectToRoute('acceuil_details', ['id' => $event->getId()]);
        }

        return $this->render('admin/events/details.html.twig', [
            'event' => $event,
            'comments' => $commentsRepository->findBy(['event' => $event], ['comment_date' => 'desc']),
            'note' => $note,
            'commentForm' => $commentForm->createView()
        ]);
    }

    #[Route('/filtre/{id}', name: 'filtre')]
    public function filtre(Request $request, EventsRepository $eventsRepository, CategoriesRepository $categoriesRepository): Response
    {
        // Verification if the param received is date or not
        if($request->get('id') == 'date'){
            $events = $eventsRepository->findBy([], ['event_date' => 'desc']);
            $filtre = 'Date';
        } else {
            $categorie = $categoriesRepository->findOneBy(['id' => $request->get('id')]);
            $events = $eventsRepository->findBy(['categorie' => $categorie]);
            $filtre = $categorie->getName();
        }
        return $this->render('main/filtre.html.twig',[
            'events' => $events,
            'filtre' => $filtre,
            'categories' => $categoriesRepository->findAll()
        ]);
    }
}

templates/main/filtre.html.twig
{% extends "base.html.twig" %}

{% block title %}Evénément filtre
{% endblock %}

{% block body %}
	<main class="container">
		<section class="row">
			<div class="row shadow-sm py-3">
				<h3 class="lead text-center my-3">Filtrer par</h3>
				<div class="d-flex justify-content-around">
					{% for category in categories %}
						<div>
							<a href="{{ path('acceuil_filtre', {id : category.id}) }}" class="btn btn-secondary">{{ category.name }}</a>
						</div>
					{% endfor %}
					<div>
						<a href="{{ path('acceuil_filtre', {id : 'date'}) }}" class="btn btn-secondary">date</a>
					</div>
				</div>
			</div>
			<h1>Affichage avec le filtre
				{{ filtre }}</h1>
			{% if events %}
				{% for event in events %}
					<div class="col-3 my-3">
						<article class="card h-100">
							<img src="{{ asset('assets/uploads/products/mini/300x300-'~ event.images[0].name ) }}" alt="{{ event.name }}" class="card-img-top">

							<div class="card-body">
								<h2>{{ event.name }}</h2>
								<p class="card-text">{{ event.description }}</p>
								{{event.eventDate | date('d/m/Y H:i')}}
								<br>
								<a href="{{path('acceuil_details', {id: event.id})}}" class="btn btn-primary my-3">Détails</a>
							</div>
						</article>
					</div>
				{% endfor %}
			{% else %}
				<p class="lead">Aucun événement n'a été trouvé</p>
			{% endif %}

		</section>
	</main>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!
{% endblock %}

{% block body %}
	<main class="container">
		<section class="row my-3">
			<h1>Gestionnaire d'événement</h1>
			<div class="row shadow-sm py-3">
				<h3 class="lead text-center my-3">Filtrer par</h3>
				<div class="d-flex justify-content-around">
					{% for category in categories %}
						<div>
							<a href="{{ path('acceuil_filtre', {id : category.id}) }}" class="btn btn-secondary">{{ category.name }}</a>
						</div>
					{% endfor %}
					<div>
						<a href="{{ path('acceuil_filtre', {id : 'date'}) }}" class="btn btn-secondary">date</a>
					</div>
				</div>
			</div>

			{% if categories is defined %}

				{% for category in categories %}
					<h1>
						<strong>{{category.name}}</strong>
					</h1>
					{% for event in events %}
						{% if event.categorie == category %}
							<div class="col-3 my-3">
								<article class="card h-100 shadow">
									<img src="{{ asset('assets/uploads/products/mini/300x300-'~ event.images[0].name ) }}" alt="{{ event.name }}" class="card-img-top">
									<div class="card-body">
										<h2>{{ event.name }}</h2>
										<p class="card-text">{{ event.description }}</p>
										<a href="{{path('acceuil_details', {id: event.id})}}" class="btn btn-primary">Détails</a>
									</div>
								</article>
							</div>
						{% endif %}

					{% endfor %}
				{% endfor %}
			{% endif %}
		</section>
	</main>
{% endblock %}

templates/main/manage.html.twig
{% extends "base.html.twig" %}

{% block title %}Gérer
{% endblock %}

{% block body %}
	<main class="container">
		<section class="row my-4">
			<h1>Bienvenue dans le menu gestion</h1>

			<div class="col">
				<table class="table my-4">
					<thead>
						<tr>
							<td>Nom</td>
							<td>Action</td>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Catgories</td>
							<td>
								<a href="{{path('admin_categories_index')}}" class="btn btn-primary">Gérer</a>
							</td>
						</tr>
						<tr>
							<td>Evénements</td>
							<td>
								<a href="{{ path('admin_events_index') }}" class="btn btn-primary">Gérer</a>
							</td>
						</tr>
						<tr>
							<td>Invités</td>
							<td>
								<a href="{{ path('admin_guests_index') }}" class="btn btn-primary">Gérer</a>
							</td>
						</tr>
						<tr>
							<td>Participants aux évenements</td>
							<td>
								<a href="{{path('admin_participants_index')}}" class="btn btn-primary">Gérer</a>
							</td>
						</tr>
						<tr>
							<td>Etudiants</td>
							<td>
								<a href="{{path('admin_students_index')}}" class="btn btn-primary">Gérer</a>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</section>
	</main>
{% endblock %}

templates/main/tableau.html.twig
{% extends "base.html.twig" %}

{% block title %}Tableau de bord
{% endblock %}

{% block body %}
	<main class="container py-3 ">
		<h1>Tableau de bord</h1>
		<div class="row mx-4 d-flex justify-content-center">
			<p class="lead text-center">Quelques participants</p>
			{% for participant in participants %}
				<div class="col-3 card my-2 py-3 ms-3 shadow-lg">
					<h5>{{ participant.user.name }}</h5>
					<p>
						Evénements :
						<strong>{{ participant.event.name }}</strong>
					</p>
				</div>
			{% endfor %}
		</div>
		<section class="row">
			<div>
				<article class="card ps-3 py-3 shadow my-3">
					<h2>Evénements</h2>
					<p>nombre total d'événement(s) :
						<strong>{{ events | length }}</strong>
					</p>
					<div class="row">
						<p>Statistiques individuelles :</p>
						{% for event in events %}
							<div class="col-2 card my-2 ms-3 shadow-lg">
								{{ event.name }}
								<p>Notes :
									{{ notes[event.name] }}
									%</p>
								<div class="progress my-2">
									<div class="progress-bar" role="progressbar" style="width: {{ notes[event.name] }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
								<a href="{{path('acceuil_details', {id : event.id})}}">Details</a>
							</div>
						{% endfor %}
					</div>
				</article>
			</div>
		</section>

		<section class="row py-3">
			<div>
				<article class="card ps-3 py-3 shadow my-3">
					<h2>Les commentaires</h2>
					<div class="row">
						{% for comment in comments %}
							<div class="col-2 card my-3 py-3 ms-3 shadow-lg">
								<p class="card-text">{{ comment.message }}
									<br>
									<em class="text-secondary">{{ comment.commentDate | date('d/m/Y H:i') }}</em>
								</p>
								<a href="{{ path('acceuil_details', {id : comment.event.id}) }}" class="btn btn-primary">Voir plus</a>
							</div>
						{% endfor %}
					</div>
				</article>
			</div>
		</section>
	</main>
{% endblock %}